export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Game} from './MainGame'
export {default as PreviousGames} from './PreviousGames'
export {default as GameLog} from './GameLog'
export {default as Register} from './Register'